<html>
<body>

<div style="width:100%;height:500;background-color:#d9edf7">

<?php echo $page->pageletData; ?>
<h5>index:model:data<h5>
<div id="pl_header">get pl_header fail </div>

<div id="pl_main">get pl_main fail</div>

<div id="pl_footer">get footer fail</div>

</div>


<script>
 var FM = (function() {
        var domid = '';
        var html  = '';
        var css   = '';
        var js    = '';
        var time  = '';

        return {
            view: function(data) {
                domid = data['domid'];
                html  = data['html'];
               
                var oPl = document.getElementById(domid);
                oPl.innerHTML = html;
            }
        }
    })();

</script>
</body>
</html>